apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: clu6-kr7fh
  name: clu6-kr7fh-dmz1-worker-ca-central-1a
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: clu6-kr7fh
      machine.openshift.io/cluster-api-machineset: clu6-kr7fh-dmz1-worker-ca-central-1a
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: clu6-kr7fh
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: clu6-kr7fh-dmz1-worker-ca-central-1a
    spec:
      providerSpec:
        value:
          ami:
            id: ami-0f6d943a1fa9172fd
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              iops: 0
              volumeSize: 120
              volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: clu6-kr7fh-worker-profile
          instanceType: m4.large
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: ca-central-1a
            region: ca-central-1
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - clu6-kr7fh-worker-sg
          subnet:
            id: subnet-090c83509f56c6666
          tags:
          - name: kubernetes.io/cluster/clu6-kr7fh
            value: owned
          userDataSecret:
            name: worker-user-data
